### ISSUE TITLE
TypeError: 'Box' object is not iterable

### ISSUE THREAD

**Issue by chenxiaohua20140401** [garethjns/reinforcement-learning-keras#29]
**hi Gareth Jones，i want test the doom example， and i have installed vizdoom and vizdoomgym， i  also verfied in anaconda terminal  whether the vizdoomgym is ok， i got the below output ：**
--------------------------------------------------------------------------
>>> env = gym.make('VizdoomBasic-v0', depth=True, labels=True, position=True, health=True)

OS: Windows NT (NT 10.0) Build 19041

D_DoomInit: Static RNGseed 1107086313 set.
M_LoadDefaults: Load system defaults.
Gameinfo scan took 0 ms
W_Init: Init WADfiles.
 adding C:/ProgramData/Anaconda3/envs/gare-rl/lib/site-packages/vizdoom/vizdoom.pk3, 583 lumps
 adding C:/ProgramData/Anaconda3/envs/gare-rl/lib/site-packages/vizdoom/freedoom2.wad, 3595 lumps
 adding C:/ProgramData/Anaconda3/envs/gare-rl/Lib/site-packages/vizdoomgym/vizdoomgym/envs/scenarios/basic.wad, 7 lumps
viz_controlled is write protected.
viz_instance_id is write protected.
C:\ProgramData\Anaconda3\envs\gare-rl\lib\site-packages\gym\logger.py:30: UserWarning: [33mWARN: Box bound precision lowered by casting to float32[0m
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))

**i think it is ok, yes? then i test the doom example then i got the error, can you give me some instructions？**
---------------------------------------------------------------------------------------------------------------
2020-10-04 16:13:42.948802: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll

OS: Windows NT (NT 10.0) Build 19041
    
D_DoomInit: Static RNGseed 1044080856 set.
M_LoadDefaults: Load system defaults.     
Gameinfo scan took 0 ms
W_Init: Init WADfiles.
 adding C:/ProgramData/Anaconda3/envs/gare-rl/lib/site-packages/vizdoom/vizdoom.pk3, 583 lumps
 adding C:/ProgramData/Anaconda3/envs/gare-rl/lib/site-packages/vizdoom/freedoom2.wad, 3595 lumps
 adding C:/ProgramData/Anaconda3/envs/gare-rl/Lib/site-packages/vizdoomgym/vizdoomgym/envs/scenarios/basic.wad, 7 lumps
viz_controlled is write protected. 
viz_instance_id is write protected.
C:\ProgramData\Anaconda3\envs\gare-rl\lib\site-packages\gym\logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))

OS: Windows NT (NT 10.0) Build 19041
    
D_DoomInit: Static RNGseed 2147483647 set.
M_LoadDefaults: Load system defaults.
Gameinfo scan took 0 ms
W_Init: Init WADfiles.
 adding C:/ProgramData/Anaconda3/envs/gare-rl/lib/site-packages/vizdoom/vizdoom.pk3, 583 lumps
 adding C:/ProgramData/Anaconda3/envs/gare-rl/lib/site-packages/vizdoom/freedoom2.wad, 3595 lumps
 adding C:/ProgramData/Anaconda3/envs/gare-rl/Lib/site-packages/vizdoomgym/vizdoomgym/envs/scenarios/basic.wad, 7 lumps
viz_controlled is write protected.
viz_instance_id is write protected.
  0%|                                                                                                                                          | 0/1000 [00:04<?, ?it/s]
Traceback (most recent call last):
  File "c:/Users/littlechen/reinforcement-learning-keras/atari-py/doom.py", line 7, in <module>
    agent.train(n_episodes=1000, max_episode_steps=10000, verbose=True, render=True)
  File "c:\Users\littlechen\reinforcement-learning-keras\atari-py\reinforcement_learning_keras\agents\agent_base.py", line 189, in train
    episode_report = self.play_episode(max_episode_steps=max_episode_steps, training=True, render=render)
  File "c:\Users\littlechen\reinforcement-learning-keras\atari-py\reinforcement_learning_keras\agents\agent_base.py", line 166, in play_episode
    total_reward, frames = self._play_episode(max_episode_steps=max_episode_steps, training=training, render=render)
  File "c:\Users\littlechen\reinforcement-learning-keras\atari-py\reinforcement_learning_keras\agents\q_learning\deep_q_agent.py", line 228, in _play_episode
    obs, reward, done, info = self.env.step(action)
  File "c:\Users\littlechen\reinforcement-learning-keras\atari-py\reinforcement_learning_keras\enviroments\atari\environment_processing\frame_buffer_wrapper.py", line 63, in step
    obs, reward, done, info = self.env.step(action)
  File "C:\ProgramData\Anaconda3\envs\gare-rl\lib\site-packages\gym\core.py", line 263, in step
    observation, reward, done, info = self.env.step(action)
  File "C:\ProgramData\Anaconda3\envs\gare-rl\lib\site-packages\vizdoomgym\vizdoomgym\envs\vizdoomenv.py", line 121, in step
    return self.__collect_observations(), reward, done, info
  File "C:\ProgramData\Anaconda3\envs\gare-rl\lib\site-packages\vizdoomgym\vizdoomgym\envs\vizdoomenv.py", line 147, in __collect_observations
    for space in self.observation_space:
TypeError: 'Box' object is not iterable

**Comment by garethjns** [comment]
Hi @chenxiaohua20140401 

I think there might be a bug in master VizDoomGym at the moment, looking at their last build it seems to be failing with similar errors https://github.com/shakenes/vizdoomgym/runs/1177614907?check_suite_focus=true , for example:

````bash
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
vizdoomgym/envs/vizdoomenv.py:121: in step
    return self.__collect_observations(), reward, done, info
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <vizdoomgym.envs.vizdoom_env_definitions.VizdoomBasic object at 0x7fc3b8fa1c10>

    def __collect_observations(self):
        observation = []
        if self.state is not None:
            observation.append(np.transpose(self.state.screen_buffer, (1, 2, 0)))
            if self.depth:
                observation.append(self.state.depth_buffer)
            if self.labels:
                observation.append(self.state.labels_buffer)
            if self.position:
                observation.append(
                    np.array([self.state.game_variables[i] for i in range(4)])
                )
                if self.health:
                    observation.append(self.state.game_variables[4])
            elif self.health:
                observation.append(self.state.game_variables[0])
        else:
            # there is no state in the terminal step, so a "zero observation is returned instead"
>           for space in self.observation_space:
E           TypeError: 'Box' object is not iterable

vizdoomgym/envs/vizdoomenv.py:147: TypeError
````

Try installing from this commit https://github.com/shakenes/vizdoomgym/tree/0320905d79a4d01948c132a0cb8c81e451bb0c67 . This is the version I currently have installed and should work. I've only set VizDoomGym up in a Ubuntu VM, though, so not sure what will happen in an Anacaonda in Windows. Please could you let me know if you get it running? I haven't had much success with training in the VizDoomGym environments yet, partly because I've been limited to running on CPU in my VM. If it runs in Aanaconda on windows it should mean I can run on my GPU instead.

**Comment by chenxiaohua20140401** [comment]
ok， it worked！ thanks！
![image](https://user-images.githubusercontent.com/37200412/95017657-4b650880-068d-11eb-9fdb-6cc3215b0ea8.png)

**Comment by garethjns** [comment]
Great! Let me know if you have success training it. So far I've managed to train the DQN in the Basic env, and have also tried in the Corridor env. It seems to start learning in Corridor, but either it gets stuck, or I haven't run it for long enough to complete it.

**Comment by chenxiaohua20140401** [comment]
> Great! Let me know if you have success training it. So far I've managed to train the DQN in the Basic env, and have also tried in the Corridor env. It seems to start learning in Corridor, but either it gets stuck, or I haven't run it for long enough to complete it.

Yes，i have completed it. However i think the agent didn‘t trained as expected as its rewards still  swing between negative number and positive number. So i think ,  i might to see the train network and hyperparameters？Did you train it successfully to get positive reward use the example network and hyperparameters？By the way，the Corridor env also normal in my computer envrioment，i could train it, it didn't stuck.
![Snipaste_2020-10-05_10-27-18](https://user-images.githubusercontent.com/37200412/95034742-69feea00-06f5-11eb-91b8-0cc34de3f207.png)

**Comment by garethjns** [comment]
For the corridor env I've seen it learn to either shoot the two guys at the start then spin around until it eventually dies, or to sprint towards the end and get killed on the way. It's better than random, but not solved.

I'm not sure if it would eventually solve the env simply with more training or if it needs tweaking to do so, perhaps with slower epsilon decay? Certainly for pong parameters like the size of the replay buffer can make the difference between solving the env and learning nothing. Also how often the target model is updated seems important too (this can be set with the "update_every" parameter).

I'm going to start experimenting a bit with it this week - I've got it running in Windows too now so can use my GPU.

Running the Basic env with these settings + the those set in VizDoomCorridorConfig looks like it works fairly well, so these are probably a good starting point:

```python
agent = DeepQAgent.example(config=VizDoomBasicConfig(agent_type='double_dueling_dqn', mode='stack'), 
                                                  n_episodes=20000, max_episode_steps=20000, 
                                                  render=False, update_every=1, checkpoint_every=1000)
    agent.save()
```
Basic env training history:
![image](https://user-images.githubusercontent.com/7212290/95070332-e0084e80-06ff-11eb-8453-129970cc307b.png)

**Comment by garethjns** [comment]
Hi @chenxiaohua20140401, if you're still interested in trying this agent on the VizDoomCorridor environment, I've just pushed a update that helps the agent a lot. It doesn't change the DQN implementation at all, rather it runs other polices ("bots") during training that contribute additional (and generally more rewarding) experience to the agent. 

![image](https://github.com/garethjns/reinforcement-learning-keras/blob/master/images/DDQN_doom_corridor_example_at_8k.gif?raw=true)

More info here: https://github.com/garethjns/reinforcement-learning-keras/blob/master/scripts/doom/README.md
