### ISSUE TITLE
TypeError: Unexpected keyword argument passed to optimizer: learning_rate

### ISSUE THREAD

**Issue by Martyanovst** [garethjns/reinforcement-learning-keras#31]
Trying to run following code for kaggle gfootball event:
```
import gfootball

from reinforcement_learning_keras.agents.components.history.training_history import TrainingHistory
from reinforcement_learning_keras.agents.components.replay_buffers.continuous_buffer import ContinuousBuffer
from reinforcement_learning_keras.agents.models.dense_nn import DenseNN
from reinforcement_learning_keras.agents.q_learning.deep_q_agent import DeepQAgent
from reinforcement_learning_keras.agents.q_learning.exploration.epsilon_greedy import EpsilonGreedy

agent = DeepQAgent(name='deep_q',
                   model_architecture=DenseNN(observation_shape=(115,), n_actions=19),
                   replay_buffer=ContinuousBuffer(buffer_size=30000),
                   env_spec="GFootball-11_vs_11_kaggle-simple115v2-v0",
                   eps=EpsilonGreedy(eps_initial=0.9, decay=0.0001, eps_min=0.01,
                                     decay_schedule='linear'),
                   training_history=TrainingHistory(agent_name='deep_q', rolling_average=1,
                                                    plotting_on=True, plot_every=5))

agent.train(verbose=True, render=False,
            n_episodes=100, max_episode_steps=3000, update_every=2,
            checkpoint_every=1)
```

Getting following exeption:
```
Traceback (most recent call last):
  File "Train.py", line 16, in <module>
    plotting_on=True, plot_every=5))
  File "<string>", line 14, in __init__
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/reinforcement_learning_keras/agents/q_learning/deep_q_agent.py", line 41, in __post_init__
    self._build_model()
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/reinforcement_learning_keras/agents/q_learning/deep_q_agent.py", line 88, in _build_model
    self._action_model = self.model_architecture.compile(model_name='action_model', loss='mse')
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/reinforcement_learning_keras/enviroments/model_base.py", line 50, in compile
    model.compile(optimizer=opt(learning_rate=self.learning_rate), loss=loss)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/keras/optimizers.py", line 471, in __init__
    super(Adam, self).__init__(**kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/tensorflow/python/keras/optimizers.py", line 68, in __init__
    'passed to optimizer: ' + str(k))
TypeError: Unexpected keyword argument passed to optimizer: learning_rate
```

reinforcement-learning-keras==0.6.1
tensorflow==2.3.1
P.S.
Sorry for my english.

**Comment by Martyanovst** [comment]
I reboot my virtual machine and problem dissapear;)

**Comment by garethjns** [comment]
Hi @Martyanovst , thanks for raising the issue and posting the update. I haven't seen that error before, but it may be due to a bug with passing args/kwargs somewhere. Let me know if it comes back and I'll take a look.
